### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by SeanAshe** [tamland/airsonic-refix#98]
Could not log in. (Unexpected token '<', "<!doctype "... is not valid JSON)
![screenshot-20230605-131055](https://github.com/tamland/airsonic-refix/assets/39847150/46880c83-3548-43c2-b10d-63cdbd7a0937)
```
version: "3"
services:
  airsonic:
    container_name: airsonic
    image: airsonic/airsonic
    restart: unless-stopped
    network_mode: bridge
    depends_on:
      - airsonic-refix
    volumes:
      - ./data:/airsonic/data
      - ./playlists:/airsonic/playlists
      - ./podcasts:/airsonic/podcasts
      - /mnt/nas/Content/Media/Music:/airsonic/music
  
  airsonic-refix:
    container_name: airsonic-refix
    image: tamland/airsonic-refix:latest
    restart: unless-stopped
    network_mode: bridge
    environment:
      - SERVER_URL=172.17.0.3:4040
    ports:
      - 8080:80
```
